### ISSUE TITLE
highlight line height doesn't match line height 

### ISSUE THREAD

**Issue by David-JA** [HeekangPark/obsidian-hk-code-block#11]
![image](https://github.com/HeekangPark/obsidian-hk-code-block/assets/80776225/44c7cd92-a0e0-4b06-bf2d-81cdd40585b7)
Could you please tell me how can I change the highlight line height? What's parameter it's related in the style.css?

**Comment by David-JA** [comment]
I have try to change the `--hk-codeblock-vertical-padding: 8px;` .But this operation seems to have no effect, changing to 6 px and 10 px, the interface remains unchanged

**Comment by vizelada15648lviki** [comment]
Hi, were you able to solve this issue? @David-JA

**Comment by chkhk** [comment]
adding this style fixes it
```css
div.hk-codeblock div.hk-codeblock-highlight > span.line {
  font-family: var(--hk-codeblock-linenos-text-font);
  font-size: var(--hk-codeblock-linenos-text-size);
  line-height: var(--line-height-normal);
}
```
